### ISSUE TITLE
Peer-review

### ISSUE THREAD

**Issue by Suzi216** [Suzi216/Portofolio#8]
**PLEASE WRITE SOME SUGGESTION TO IMPROVE THE CODE**

**Comment by HatimDev-HE** [comment]
## STATUS: APPROVE ✔️ ✔️ 🍾
Hi @Suzi216 ,
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉 👏 👏 💯
![you did it gif](https://user-images.githubusercontent.com/102610715/174246520-7bb8fd2d-d656-42e8-a7bd-8202fffe7728.gif)

## To highlight 🍾
1. All linters are passing ✔️
2. Good commit history ✔️
3. Good PR description ✔️
4. Your README file is professional ✔️
5. Follow GitHub workflow ✔️

Cheers and Happy coding!👏👏👏

**Comment by Lasten-Ernest** [comment]
Hello Suzana, 
You have done nice work.

- Meaningful Html tags
- clean code, no unnecessary line spaces
- Meaningful commit messages
- Images have alternative texts.

Well done!!! 👏👏
